#!/bin/bash

# Use of command line arguments 
# To run this script do like this: " ./cmdlinearguments4 hello_nix hello_neha "
# As you can see the arguments are lined up using $0,1,2 etc that argument will get passed according to it's priority that is given by the $number

echo "script name: $1"
echo "First argument: $2"
echo "Second argument: $0"
