#!/bin/bash
clear
# script to run the number of seconds 
count=0
num=100
# Here, There is "[ $count -lt 100 ]; do" this condition means that while loop will run as long as the count is less than 100

while [ $count -lt 100 ]; do
echo
echo $num of seconds left to stop this process $1
echo 
sleep 1
num=`expr $num - 1`
count=`expr $count + 1`
done

echo
echo $1 process is stopped!!!!
echo
